"""Register the verified model back into DataHub.

Reading the catalog to write better code only helps the person running the
agent. Writing the result back is what makes the next person -- or the next
agent -- inherit the work: the new model appears as a dataset with real
column-level lineage to its sources, the governance tags it inherited, and a
description recording that it was machine-verified.

Lineage and schema go through the DataHub SDK (there is no MCP tool that creates
a dataset). Tags and descriptions go through MCP mutation tools, which is the
interface the hackathon's agent stack exposes.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .artifact import Artifact
from .context import CatalogContext
from .gates.governance import is_sensitive


@dataclass
class WriteBackPlan:
    """What we intend to put in the graph, decided before anything is sent."""

    urn: str
    description: str
    upstreams: list[str] = field(default_factory=list)
    column_lineage: list[tuple[str, str, str]] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)

    def summary(self) -> str:
        lines = [f"dataset {self.urn}"]
        lines.append(f"  upstreams: {len(self.upstreams)}")
        lines.append(f"  column lineage edges: {len(self.column_lineage)}")
        lines.append(f"  tags: {', '.join(self.tags) if self.tags else '(none)'}")
        return "\n".join(lines)


def make_urn(name: str, platform: str = "dbt", env: str = "PROD") -> str:
    return f"urn:li:dataset:(urn:li:dataPlatform:{platform},{name},{env})"


def plan_writeback(
    artifact: Artifact,
    context: CatalogContext,
    attempts: int,
    platform: str = "dbt",
) -> WriteBackPlan:
    """Derive the graph contribution from what the artifact actually references.

    Tags are inherited rather than invented: if the model reads a PII column,
    the model is PII. That propagation is the whole point of doing this in the
    catalog instead of a comment in the repo.
    """
    upstreams = sorted({urn for urn, _ in artifact.column_refs})

    inherited: set[str] = set()
    column_lineage: list[tuple[str, str, str]] = []
    for urn, column in artifact.column_refs:
        column_lineage.append((urn, column, artifact.output_name))
        for tag in context.tags_for_column(urn, column) or ():
            if is_sensitive(tag):
                inherited.add(tag)

    verdict = "verified" if attempts else "unverified"
    description = (
        f"{artifact.description}\n\n"
        f"Generated by Groundskeeper and {verdict} against the catalog "
        f"(field existence, governance, and execution) in {attempts} attempt(s)."
    ).strip()

    return WriteBackPlan(
        urn=make_urn(artifact.output_name, platform=platform),
        description=description,
        upstreams=upstreams,
        column_lineage=column_lineage,
        tags=sorted(inherited),
    )


def emit(plan: WriteBackPlan, gms_url: str, token: str | None = None) -> None:
    """Send the plan to DataHub: dataset properties, lineage, then tags."""
    from datahub.emitter.mce_builder import make_tag_urn
    from datahub.emitter.mcp import MetadataChangeProposalWrapper
    from datahub.emitter.rest_emitter import DatahubRestEmitter
    from datahub.metadata.schema_classes import (
        DatasetPropertiesClass,
        GlobalTagsClass,
        TagAssociationClass,
        UpstreamClass,
        UpstreamLineageClass,
    )

    emitter = DatahubRestEmitter(gms_server=gms_url, token=token)

    emitter.emit(
        MetadataChangeProposalWrapper(
            entityUrn=plan.urn,
            aspect=DatasetPropertiesClass(description=plan.description),
        )
    )

    if plan.upstreams:
        emitter.emit(
            MetadataChangeProposalWrapper(
                entityUrn=plan.urn,
                aspect=UpstreamLineageClass(
                    upstreams=[
                        UpstreamClass(dataset=u, type="TRANSFORMED")
                        for u in plan.upstreams
                    ]
                ),
            )
        )

    if plan.tags:
        emitter.emit(
            MetadataChangeProposalWrapper(
                entityUrn=plan.urn,
                aspect=GlobalTagsClass(
                    tags=[TagAssociationClass(tag=make_tag_urn(t)) for t in plan.tags]
                ),
            )
        )
